[[junction]]
	name = "junction_test"
	min = true
	sequence = [
	["TCTTCTATACTGGCAAAAAAAAAACAGGATTAGCAGAG"],
	["TCTTCTATACTGGCAAAAAAAAAACAGGATTAGCAGAG"],
	["TCTTCTATACTGGCAAAAAAAAAACAGGATTAGCAGAG"]
	]
