[[HEG]]
	file = "linkers/HEG.pdb"
	linkerS = 1
	linkerSName = "C8"
	linkerSResnum = 1
	linkerE = 17
	linkerEName = "C12"
	linkerEResnum = 1
	linkerCenter = "O1"

[[4T]]
        file = "linkers/4T.pdb"
        linkerS = 8 # looks like an atom index
        linkerSName = "C3'" # atom.pdbname
        linkerSResnum = 2 
        linkerE = 96
        linkerEName = "P"
        linkerEResnum = 5
        linkerCenter = "P*"

[[benzene]]
	file = "linkers/benzene.pdb"
	linkerS = 7
	linkerSName = "C7"
	linkerSResnum = 1
	linkerE = 13
	linkerEName = "C13"
	linkerEResnum = 1
	linkerCenter = "C5"
