[[HEG]]
	file = "linkers/HEG.pdb"
	linkerS = 1
	linkerSName = "C8"
	linkerSResnum = 1
	linkerE = 17
	linkerEName = "C12"
	linkerEResnum = 1
	linkerCenter = "O1"

[[4T]]
	file = "linkers/4T.pdb"
	linkerS = 1 #was 5
	linkerSName = "P" # was C5*
	linkerSResnum = 1
	linkerE = 102
	linkerEName = "P"
	linkerEResnum = 5
	linkerCenter = "P*"

[[benzene]]
	file = "linkers/benzene.pdb"
	linkerS = 7
	linkerSName = "C7"
	linkerSResnum = 1
	linkerE = 13
	linkerEName = "C13"
	linkerEResnum = 1
	linkerCenter = "C5"
